# first work for jumia website

In [1]:
from bs4 import BeautifulSoup as bs
import requests
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

page = 1
t = {"num_of_people_rated":[], 
     'Rating':[], 
     'discount': [], 
     'new_price':[], 
     'old_price':[], 
     'all_items_name':[]}

while page <= 50:
    url = "https://www.jumia.com.ng/catalog/?q=shoes&page={}#catalog-listing".format(page)
    html = requests.get(url)
    soup = bs(html.content)
    
    for i in soup.find_all("a", class_ = "core"):
        try:
            t['old_price'].append(i.find("div", class_ = "old").text)
        except:
            t['old_price'].append(np.nan)
        try:
             t['new_price'].append(i.find("div", class_ = "prc").text)
        except:
                t['new_price'].append(np.na)
        try:
              t['all_items_name'].append(i.find("h3", class_ = "name").text)
        except:
                t['all_items_name'].append(np.nan)
        try:
              t['discount'].append(i.find("div", class_ = "bdg _dsct _sm").text)
        except:
                t['discount'].append(np.nan) 
        try:
             t['Rating'].append(i.find("div", class_ = "stars _s").text)
        except:
                t['Rating'].append(np.nan)
        try:
             t["num_of_people_rated"].append(i.find("div", class_ = "rev").text.split('(')[1].strip(')'))
        except:
            t["num_of_people_rated"].append(np.nan)
    page+=1

In [3]:
df = pd.DataFrame(t)
df

,num_of_people_rated,Rating,discount,new_price,old_price,all_items_name
0,12,4.5 out of 5,55%,"₦ 22,958","₦ 51,017",ADIDAS Advantage Lifestyle Court Lace Shoes
1,287,3.7 out of 5,51%,"₦ 4,785","₦ 9,800",Men Leather Loafers & Slip-Ons
2,32,4.3 out of 5,9%,"₦ 26,200","₦ 28,798",Male Formal Shoes Glossy Tassel Brogue Leather...
3,39,3.9 out of 5,54%,"₦ 11,000","₦ 24,000",Men's Sneakers Canvas-BROWN
4,94,3.6 out of 5,28%,"₦ 6,480","₦ 9,000",Classic Business Men Cooperate Leather Shoes- ...
5,37,4 out of 5,43%,"₦ 5,999","₦ 10,000 - ₦ 10,500",Solid Kids Shoe- Black
6,27,4.1 out of 5,32%,"₦ 23,950","₦ 35,000",Depally Men's Brogue Tie Designers Shoe Black
7,12,4.2 out of 5,14%,"₦ 12,780","₦ 14,800",Mens Basket Leather Half Shoe - Black
8,24,4.3 out of 5,24%,"₦ 15,200","₦ 20,118",Men Sandals Handmade Leather Breathable Hiking...
9,20,3.4 out of 5,47%,"₦ 4,800","₦ 9,000",Executive Business Men Leather Loafer Shoes- B...
10,11,4 out of 5,40%,"₦ 16,980","₦ 28,500",DEPALLY IRON CHAIN TIE SHINING BLACK SHOE
11,42,3.8 out of 5,54%,"₦ 11,000","₦ 24,000",Cooperate Business Men's Leather Luxury Weddin...
12,9,3.1 out of 5,50%,"₦ 15,000","₦ 30,000",Mens Simple Half Shoe - Black
13,31,3.8 out of 5,44%,"₦ 13,999 - ₦ 15,500","₦ 25,000",Mens Basket Leather Half Shoe - Black
14,92,4.3 out of 5,NaN,"₦ 12,000",NaN,ElegantMen's Half Shoe
15,32,3.8 out of 5,29%,"₦ 8,549","₦ 12,000",Stainless Shoe Rack + Steel Pipes For 20 Pairs...
16,65,4.2 out of 5,27%,"₦ 23,500","₦ 32,000",Male Formal Shoes Glossy Tassel Brogue Leather...
17,154,4 out of 5,37%,"₦ 18,995","₦ 30,000",Classy 3 Column Mobile Steel Wardrobe Closet
18,2,4.5 out of 5,53%,"₦ 15,400","₦ 33,000",Vangelo H CONFIRM ITALIAN LEATHER BLACK SHOES
19,19,3.4 out of 5,9%,"₦ 10,000","₦ 11,000",Mens Basket Leather Half Shoe - Black
20,44,4.3 out of 5,62%,"₦ 11,500","₦ 30,000",Santiago 2022 Mens Executive Business Office C...
21,75,4.4 out of 5,4%,"₦ 11,500","₦ 12,000",Mens Casual Half Shoes Party Footwear-Black Ha...
22,89,4.1 out of 5,49%,"₦ 13,800","₦ 26,800",2024 Men's Fashion Dress Shoes - Black
23,51,4 out of 5,25%,"₦ 13,499 - ₦ 13,999","₦ 18,000",Mens Basket Leather Half Shoe - Black
24,61,4.1 out of 5,45%,"₦ 27,200","₦ 49,286",Male Formal Shoes Glossy Tassel Brogue Leather...
25,26,3.8 out of 5,60%,"₦ 12,000","₦ 30,000",Decent Half Shoe
26,6,4 out of 5,47%,"₦ 16,000","₦ 30,000",Mens Leather Half Shoe - Black
27,43,4.2 out of 5,64%,"₦ 10,875 - ₦ 11,309","₦ 30,000",Santiago Mens Dress Shoes Italian Leather Shoe...
28,6,4.3 out of 5,37%,"₦ 18,600","₦ 29,500",DEPALLY CHAIN IRON TIE DESIGNERS SHOES BLACK
29,49,3.9 out of 5,66%,"₦ 10,300","₦ 30,000",Varrati [NEW] Mens Leisure Dress Italian Leath...
30,67,4.4 out of 5,64%,"₦ 10,875","₦ 30,000",Santiago New Men Italian Fashion Office Shoes...
31,24,3.4 out of 5,31%,"₦ 17,900","₦ 25,000 - ₦ 26,000",Black Classic Men's Fashion Shoes
32,19,3.9 out of 5,30%,"₦ 13,520","₦ 19,404",2022 Men's Casual Shoes Breathable Shoes
33,102,4.4 out of 5,NaN,"₦ 10,899",NaN,Stainless Shoe Rack + Steel Pipes (6 Layers)
34,111,4.2 out of 5,34%,"₦ 19,000","₦ 28,704",Men Glossy Tassel Brogue Leather Shoes Loafers...
35,5,3.6 out of 5,47%,"₦ 9,500","₦ 18,000",Mens Black Basket Cover Palm
36,2,5 out of 5,47%,"₦ 16,000","₦ 30,000",Black Men's Decent Half Shoe
37,33,4.2 out of 5,73%,"₦ 12,150","₦ 45,000",FOLLETEL NEW Mens Office Wedding Leisure Itali...
38,70,4 out of 5,14%,"₦ 13,800","₦ 16,000",Men's Formal Italian Wedding Brogues Leather S...
39,29,4 out of 5,27%,"₦ 14,900","₦ 20,500",Men Corporate Shoes - Office Shoe - Leather - ...

# Waterstones website

In [6]:
from selenium import webdriver # for controlling web browser

from selenium.webdriver.chrome.service import Service as ChromeService

# part of the Selenium Library for configuring Chrome browser settings.
import requests
from bs4 import BeautifulSoup

y = {"author_of_book": [],
     "title_of_book" :[],
     "cover_type" :[],
    "new_price": [],
      "old_price" : [],
    "stock_availability": []}

page = 1
while page <=50:
    url = 'https://www.waterstones.com/books/bestsellers/sort/bestselling/page/{}'.format(page)
    path = 'C:/Users/KENNETH/Documents/LASOP DATA SCIENCE/SOFTWARE/chromedriver-win64/chromedriver.exe'


    # set up the Chrome webdriver
    chrome_service = ChromeService(executable_path=path)
    driver = webdriver.Chrome(service=chrome_service)

    # Open the webpage
    driver.get(url)

    # wait for the page to load(you might need to adjust the waiting time)
    #driver.implicitly_wait(10)

    # # Get the page source after Javascript execution
    page_source = driver.page_source

    soup =BeautifulSoup(page_source, 'html.parser')

    import pandas as pd

    for i in soup.find_all('div', class_='info-wrap'):
        try:
            y["author_of_book"].append(i.find('span', class_='author').text.strip())
        except:
             y["author_of_book"].append(np.nan)

        try:
            y["title_of_book"].append(i.find('div', class_='title-wrap').text.strip())
        except:
              y["title_of_book"].append(np.nan)

        try:
            y["cover_type"].append(i.find('div', class_='book-price').find_all("span")[-1].text.strip())
        except:
            y["cover_type"].append(np.nan)

        try:
            y["new_price"].append(i.find('span', class_="price").text)
        except:
            y["new_price"].append(np.nan)

        try: 
            y["old_price"].append(i.find('span', class_='price-rrp').text)
        except:
            y["old_price"].append(np.nan)

        try:
             y["stock_availability"].append(i.find('span', class_="format").text)
        except:
             y["stock_availability"].append(np.nan)


    page +=1
    
df= pd.DataFrame(y)
df.to_csv("book.csv", index=False)

In [7]:
df

,author_of_book,title_of_book,cover_type,new_price,old_price,stock_availability
0,G. T. Karber,Murdle,Paperback,£14.99,NaN,In stock online
1,Gabrielle Zevin,Tomorrow…,Paperback,£8.49,£9.99,In stock online
2,Rory Stewart,Politics On the…,Hardback,£18.99,£22.00,In stock online
3,David Grann,The Wager,Paperback,£8.99,£10.99,In stock online
4,Alice Oseman,Heartstopper…,Paperback,£10.99,£12.99,In stock online
...,...,...,...,...,...,...
115,Pan Macmillan,Match Annual…,Hardback,£2.99,£9.99,In stock online
116,Ian Rankin,A Heart Full…,Paperback,£7.99,£9.99,In stock online
117,Dolly Alderton,Good Material,Hardback,£15.99,£18.99,In stock online
118,Sarah J. Maas,House of…,Hardback,£18.99,£22.00,Pre-order
119,Michael Palin,Great-Uncle…,Hardback,£11.00,£22.00,In stock online